<h2>Training bearbeiten</h2>
<form action="/minitrm/index.php?controller=training&action=trainingbearbeiten" name="neueexcercise" method="post">
    <input type="hidden" name="controller" value="training">
    <input type="hidden" name="action" value="trainingbearbeiten">
    <input type="hidden" name="id" value="<?php echo $collection3->id; ?>">
    <div>
        <h3>
        User
        </h3>
        <select name="user_id">
        <?php
        foreach ($collection as $person) {
            $selected = "";
            if ($person->id == $collection3->user_id)
                $selected = "selected";
        ?>
            <option value="<?php echo $person->id; ?>" <?php echo $selected; ?>><?php echo $person->firstname . " " . $person->lastname; ?></option>
        <?php
        }
        ?>
        </select>
    </div>
    <div>
        <h3>
        Split
        </h3>
        <select name="split_id">
        <?php
        foreach ($collection2 as $split) {
            $selected = "";
            if ($split->id == $collection4->split_id)
                $selected = "selected";
        ?>
            <option value="<?php echo $split->id; ?>" <?php echo $selected; ?>><?php echo $split->name . ", " . $split->part; ?></option>
        <?php
        }
        ?>
        </select>
    </div>
    <div>
        <h3>
        Day
        </h3>
        <input type="text" name="day" value="<?php echo $collection3->day; ?>">
    </div>
    <div>
        <h3>
        User Weight
        </h3>
        <input type="text" name="user_weight" value="<?php echo $collection3->user_weight; ?>">
    </div>
    <div>
        <h3>
        User Scope
        </h3>
        <input type="text" name="user_scope" value="<?php echo $collection3->user_scope; ?>">
    </div>
    <div>
        <h3>
        User Leg
        </h3>
        <input type="text" name="user_leg" value="<?php echo $collection3->user_leg; ?>">
    </div>
    <div>
        <h3>
        User Arm
        </h3>
        <input type="text" name="user_arm" value="<?php echo $collection3->user_arm; ?>">
    </div>
    <br>
    <div id="speichern">
        <input type="submit" value="speichern">
    </div>
</form>
<p><a href="index.php?controller=index&action=index">zur&uuml;ck</a></p>