<h2>Training anlegen</h2>
<form action="/minitrm/index.php?controller=training&action=traininganlegen" name="neueexcercise" method="post">
    <input type="hidden" name="controller" value="training">
    <input type="hidden" name="action" value="traininganlegen">
    <div>
        <h2>
            Neues Training
        </h2>
    </div>
    <div>
        <h3>
        User
        </h3>
        <select name="user_id">
        <?php
        foreach ($collection as $person) {
        ?>
            <option value="<?php echo $person->id; ?>"><?php echo $person->firstname . " " . $person->lastname; ?></option>
        <?php
        }
        ?>
        </select>
    </div>
    <div>
        <h3>
        Split
        </h3>
        <select name="split_id">
        <?php
        foreach ($collection2 as $split) {
        ?>
            <option value="<?php echo $split->id; ?>"><?php echo $split->name . ", " . $split->part; ?></option>
        <?php
        }
        ?>
        </select>
    </div>
    <div>
        <h3>
        Day
        </h3>
        <input type="text" name="day">
    </div>
    <div>
        <h3>
        User Weight
        </h3>
        <input type="text" name="user_weight">
    </div>
    <div>
        <h3>
        User Scope
        </h3>
        <input type="text" name="user_scope">
    </div>
    <div>
        <h3>
        User Leg
        </h3>
        <input type="text" name="user_leg">
    </div>
    <div>
        <h3>
        User Arm
        </h3>
        <input type="text" name="user_arm">
    </div>
    <br>
    <div id="speichern">
        <input type="submit" value="speichern">
    </div>
</form>
<p><a href="index.php?controller=index&action=index">zur&uuml;ck</a></p>