<h2>Sets</h2>
<?php
?>
<table border="1">
    <thead>
        <th>ID</th>
        <th>Training ID</th>
        <th>Weight</th>
        <th>Repetitions</th>
    </thead>
            <?php
            //foreach $collection $person
            //TODO $person instanziieren
            foreach ($collection as $split) {
            ?>
            
    <tr>
        <td>
            <?php echo $split->id; ?>
        </td>
        <td>
            <?php echo $split->training_id; ?>
        </td>
        <td>
            <?php echo $split->weight; ?>
        </td>
        <td>
            <?php echo $split->repetitions; ?>
        <td valign="top">
            <a href="/minitrm/index.php?controller=sets&action=setsbearbeiten&id=<?php echo $split->id; ?>">bearbeiten</a>
            <a href="/minitrm/index.php?controller=sets&action=setsdelete&id=<?php echo $split->id; ?>">delete</a>
        </td>
    </tr>
    <?php
            }
    ?>
</table>
<p><a href="index.php?controller=index&action=index">zur&uuml;ck</a></p>