<?php
if (isset($_POST['action'])) {
?>
<h2>Die Excercise wurde angepasst.</h2>
<?php
} else {
?>
<h2>Excercise bearbeiten</h2>
<form action="/minitrm/index.php?controller=excercise&action=excercisebearbeiten" name="neueexcercise" method="post">
    <input type="hidden" name="controller" value="excercise">
    <input type="hidden" name="action" value="excercisebearbeiten">
    <input type="hidden" name="id" value="<?php echo $excercise->id; ?>">
    <div>
        <h3>
        Split, Part
        </h3>
        <select name="split">
            <option value="">--Bitte auswählen--</option>
        <?php
        foreach ($splits as $split) {
            $selected = "";
            if ($split->id == $excercise->split_id)
                $selected = "selected";
        ?>
            <option value="<?php echo $split->id; ?>" <?php echo $selected; ?>><?php echo $split->name . ", " . $split->part; ?></option>
        <?php
        }
        ?>
        </select>
    </div>
    <div>
        <h3>
        User
        </h3>
        <select name="user">
            <option value="">--Bitte auswählen--</option>
        <?php
        foreach ($personlist as $persone) {
            $selected = "";
            if ($persone->id == $excercise->user_id)
                $selected = "selected";
        ?>
            <option value="<?php echo $persone->id; ?>" <?php echo $selected; ?>><?php echo $persone->firstname . " " . $persone->lastname; ?></option>
        <?php
        }
        ?>
        </select>
    </div>
    <div>
        <h3>
        Name
        </h3>
        <input type="text" name="name" value="<?php echo $excercise->name; ?>">
    </div>
    <div>
        <h3>
        Number
        </h3>
        <input type="text" name="number" value="<?php echo $excercise->number; ?>">
    </div>
    <div>
        <h3>
        Sets
        </h3>
        <input type="text" name="sets" value="<?php echo $excercise->sets; ?>">
    </div>
    <div>
        <h3>
        Reps
        </h3>
        <input type="text" name="reps" value="<?php echo $excercise->reps; ?>">
    </div>
    <div>
        <h3>
        Sequence
        </h3>
        <input type="text" name="sequence" value="<?php echo $excercise->sequence; ?>">
    </div>
    <br>
    <div id="speichern">
        <input type="submit" value="speichern">
    </div>
</form>
<?php
}
?>
<p><a href="index.php?controller=index&action=index">zur&uuml;ck</a></p>