<h2>User bearbeiten</h2>
<form action="/minitrm/index.php?controller=person&action=personbearbeiten" name="neueperson" method="post">
    <input type="hidden" name="controller" value="person">
    <input type="hidden" name="action" value="personbearbeiten">
    <input type="hidden" name="id" value="<?php echo $person->id; ?>">
    <input type="hidden" name="gespeichert" value="1">
    <div id="ueberschrift">
        <h2>
            Person
        </h2>
    </div>
    <div id="vorname">
        <h3>
            Vorname
        </h3>
        <input type="text" name="firstname" value="<?php echo $person->firstname; ?>">
    </div>
    <div id="nachname">
        <h3>
            Nachname
        </h3>
        <input type="text" name="lastname" value="<?php echo $person->lastname; ?>">
    </div>
    <br>
    <div id="speichern">
        <input type="submit" name="speichern" value="speichern">
    </div>
</form>
<p><a href="index.php?controller=index&action=index">zur&uuml;ck</a></p>