<?php
if (isset($_POST['action'])) {
?>
<h2>Der User wurde angelegt.</h2>
<?php
} else {
?>
<h2>User anlegen</h2>
<form action="/minitrm/index.php?controller=person&action=personanlegen" name="neueperson" method="post">
    <input type="hidden" name="controller" value="person">
    <input type="hidden" name="action" value="personanlegen">
    <div id="ueberschrift">
    <div id="vorname">
        <h3>
            Vorname
        </h3>
        <input type="text" name="firstname">
    </div>
    <div id="nachname">
        <h3>
            Nachname
        </h3>
        <input type="text" name="lastname">
    </div>
    <br>
    <div id="speichern">
        <input type="submit" value="speichern">
    </div>
</form>
<?php
}
?>
<p><a href="index.php?controller=index&action=index">zur&uuml;ck</a></p>