<form action="/minitrm/index.php?controller=person&action=personanlegen" name="neueperson" method="get">
    <input type="hidden" name="controller" value="person">
    <input type="hidden" name="action" value="personanlegen">
    <div id="ueberschrift">
        <h2>
            Neue Person
        </h2>
    </div>
    <div id="vorname">
        <h3>
            Vorname
        </h3>
        <input type="text" name="firstname">
    </div>
    <div id="nachname">
        <h3>
            Nachname
        </h3>
        <input type="text" name="lastname">
    </div>
    <br>
    <div id="speichern">
        <input type="submit" value="speichern">
    </div>
</form>